#Colores
set -g default-terminal "screen-256color"

#Prefix ya va a ser ctrl+a
set -g prefix C-a
bind C-a send-prefix
unbind C-b

#Ctrl-a + r recarga la configuración de tmux
bind r source-file ~/.tmux.conf

#Cambiar el título de la terminal por usuario@host y las ips privadas y pública
set -g set-titles on
#set -g set-titles-string '#(whoami)@#h  #(hostname -i -I;echo)/#(curl canihazip.com/s;echo)'

#Usar los keybindings de vi
setw -g mode-keys vi

#Moverse entre paneles usando hjkl
unbind-key j
bind-key j select-pane -D
unbind-key k
bind-key k select-pane -U
unbind-key h
bind-key h select-pane -L
unbind-key l
bind-key l select-pane -R

#tmux-powerline
set-option -g status on
set-option -g status-interval 2
set-option -g status-justify "centre"
set-option -g status-left-length 120
set-option -g status-right-length 120

unbind p
bind p paste-buffer
#bind-key -T copy-mode-vi v send-keys -X begin-selection
#bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

set-option -g default-command /bin/zsh
set-option -g default-shell /bin/zsh

source ".tmuxlinerc"
